# -*- coding: utf-8 -*-
"""Лабораторная 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVjuSFAP0A7D-B1FrjF6ON6duJ5npmi6
"""

# Лабораторная 1

# Задачи повышшенной сложности

# 1 Задача

n = int(input())
days = n // (3600 * 24)
hours = (n - days * 3600 * 24) // 3600
mins = n // 60 % 60
print(f'{days}:{hours}:{mins}')

# 2 Задача

n = int(input())
nn = str(n) + str(n)
nnn = nn + str(n)
res = n + int(nn) + int(nnn)
print(res)